/*
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.11.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GeoPoint;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Location description
 */
@ApiModel(description = "Location description")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-19T22:49:09.515+01:00")
public class LocationDescription {
  @SerializedName("pictures")
  private List<UUID> pictures = null;

  @SerializedName("location")
  private GeoPoint location = null;

  @SerializedName("description")
  private String description = null;

  public LocationDescription pictures(List<UUID> pictures) {
    this.pictures = pictures;
    return this;
  }

  public LocationDescription addPicturesItem(UUID picturesItem) {
    if (this.pictures == null) {
      this.pictures = new ArrayList<UUID>();
    }
    this.pictures.add(picturesItem);
    return this;
  }

   /**
   * Location pictures
   * @return pictures
  **/
  @ApiModelProperty(value = "Location pictures")
  public List<UUID> getPictures() {
    return pictures;
  }

  public void setPictures(List<UUID> pictures) {
    this.pictures = pictures;
  }

  public LocationDescription location(GeoPoint location) {
    this.location = location;
    return this;
  }

   /**
   * Location
   * @return location
  **/
  @ApiModelProperty(value = "Location")
  public GeoPoint getLocation() {
    return location;
  }

  public void setLocation(GeoPoint location) {
    this.location = location;
  }

  public LocationDescription description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationDescription locationDescription = (LocationDescription) o;
    return Objects.equals(this.pictures, locationDescription.pictures) &&
        Objects.equals(this.location, locationDescription.location) &&
        Objects.equals(this.description, locationDescription.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pictures, location, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationDescription {\n");
    
    sb.append("    pictures: ").append(toIndentedString(pictures)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

