/*
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.11.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.GeoPoint;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Wielokąt
 */
@ApiModel(description = "Wielokąt")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-19T22:49:09.515+01:00")
public class Polygon {
  @SerializedName("points")
  private List<GeoPoint> points = new ArrayList<GeoPoint>();

  public Polygon points(List<GeoPoint> points) {
    this.points = points;
    return this;
  }

  public Polygon addPointsItem(GeoPoint pointsItem) {
    this.points.add(pointsItem);
    return this;
  }

   /**
   * Punkty
   * @return points
  **/
  @ApiModelProperty(required = true, value = "Punkty")
  public List<GeoPoint> getPoints() {
    return points;
  }

  public void setPoints(List<GeoPoint> points) {
    this.points = points;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Polygon polygon = (Polygon) o;
    return Objects.equals(this.points, polygon.points);
  }

  @Override
  public int hashCode() {
    return Objects.hash(points);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Polygon {\n");
    
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

